version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Zipping deployment package.. for ProduceAirbnbBookingData"
      - cd ProduceAirbnbBookingData
      - pip install -r requirements.txt -t lib
      - cd lib
      - zip -r9 ../deployment_package_ProduceAirbnbBookingData.zip .
      - cd ..
      - zip -g deployment_package_ProduceAirbnbBookingData.zip lambda_function.py
      - cd ..
      - echo "Zipping deployment package.. for FilterAirbnbBookingData"
      - cd FilterAirbnbBookingData
      - pip install -r requirements.txt -t lib
      - cd lib
      - zip -r9 ../deployment_package_FilterAirbnbBookingData.zip .
      - cd ..
      - zip -g deployment_package_FilterAirbnbBookingData.zip lambda_function.py
      - cd ..
      - echo "Zipping deployment package.. for TargetAirbnbBookingData"
      - cd TargetAirbnbBookingData
      - pip install -r requirements.txt -t lib
      - cd lib
      - zip -r9 ../deployment_package_TargetAirbnbBookingData.zip .
      - cd ..
      - zip -g deployment_package_TargetAirbnbBookingData.zip lambda_function.py
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda function - ProduceAirbnbBookingData"
      - cd ProduceAirbnbBookingData
      - aws s3 cp deployment_package_ProduceAirbnbBookingData.zip s3://lambda-builds-zip-class3/
      - cd ../FilterAirbnbBookingData
      - aws s3 cp deployment_package_FilterAirbnbBookingData.zip s3://lambda-builds-zip-class3/
      - cd ../TargetAirbnbBookingData
      - aws s3 cp deployment_package_TargetAirbnbBookingData.zip s3://lambda-builds-zip-class3/
      - cd ..
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name ProduceAirbnbBookingData --s3-bucket lambda-builds-zip-class3 --s3-key deployment_package_ProduceAirbnbBookingData.zip
      - aws lambda update-function-code --function-name FilterAirbnbBookingData --s3-bucket lambda-builds-zip-class3 --s3-key deployment_package_FilterAirbnbBookingData.zip
      - aws lambda update-function-code --function-name get-event-from-eventbridge-pipe-class4 --s3-bucket lambda-builds-zip-class3 --s3-key deployment_package_TargetAirbnbBookingData.zip
      - echo "Deployment complete!"